#!/bin/bash

# **********************************************************************
#
# Copyright (c) 2003-2008 ZeroC, Inc. All rights reserved.
#
# This copy of Ice is licensed to you under the terms described in the
# ICE_LICENSE file included in this distribution.
#
# **********************************************************************

if [ $# != 3 ]
then 
   echo Usage: ${0} \<source-include\> \<destination-include\> \<subdirs\>
   exit 1
fi

source=${1}
dest=`cd ${2}; pwd`
subdirs=${3}

cd $source

commands=
tokens=

for i in $subdirs
do
   if [ -d $i ]
   then 
      commands="${commands}s%${i}/%${i}Cpp/%g;"
      tokens="${tokens} $i"
   fi
done

for i in $tokens
do 
   desti=${dest}/${i}Cpp
   if [ ! -d $desti ]; then mkdir $desti ; fi

   echo Processing $i headers
   cd $i
   for h in *.h
   do
      sed -e ${commands} $h > ${desti}/${h} 
   done
   cd ..
done






