# **********************************************************************
#
# Copyright (c) 2003-2009 ZeroC, Inc. All rights reserved.
#
# This copy of Ice FIX is licensed to you under the terms described in the
# ICE_FIX_LICENSE file included in this distribution.
#
# **********************************************************************

top_srcdir	= ../..

TARGETS		= 

include $(top_srcdir)/config/Make.rules

clean::
	-rm -rf db/node/* db/registry/*
	-rm -rf db-tp1/data/* db-tp1/logs/* store/*
