DispatcherTest.m: DispatcherTest.ice "$(slicedir)/Ice/BuiltinSequences.ice"
DispatcherTest.cpp: DispatcherTest.ice "$(slicedir)/Ice/BuiltinSequences.ice" "$(SLICE2CPP)" "$(SLICEPARSERLIB)"
DispatcherTest.m: DispatcherTest.ice "$(slicedir)/Ice/BuiltinSequences.ice"
DispatcherTest.cpp: DispatcherTest.ice "$(slicedir)/Ice/BuiltinSequences.ice" "$(SLICE2CPP)" "$(SLICEPARSERLIB)"
DispatcherTest.m: DispatcherTest.ice "$(slicedir)/Ice/BuiltinSequences.ice"
DispatcherTest.cpp: DispatcherTest.ice "$(slicedir)/Ice/BuiltinSequences.ice" "$(SLICE2CPP)" "$(SLICEPARSERLIB)"
