// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `EndpointTypes.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

var __ice_EnumBase = require("./EnumBase");
var __ice_HashMap = require("./HashMap");

var Ice = (function(_mod_Ice, undefined)
{

    /// <summary>
    /// Determines the order in which the Ice run time uses the endpoints
    /// in a proxy when establishing a connection.
    /// </summary>
    
    _mod_Ice.EndpointSelectionType = function(_n, _v)
    {
        __ice_EnumBase.call(this, _n, _v);
    }
    _mod_Ice.EndpointSelectionType.prototype = new __ice_EnumBase();
    _mod_Ice.EndpointSelectionType.prototype.constructor = _mod_Ice.EndpointSelectionType;
    Object.defineProperty(_mod_Ice.EndpointSelectionType, 'Random', {
        enumerable: true,
        value: new _mod_Ice.EndpointSelectionType("Random", 0)
    });
    Object.defineProperty(_mod_Ice.EndpointSelectionType, 'Ordered', {
        enumerable: true,
        value: new _mod_Ice.EndpointSelectionType("Ordered", 1)
    });

    return _mod_Ice;
}(Ice || {}));

module.exports.Ice = Ice;
