// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `Router.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

var __ice_Object = require("./Object");
var __ice_ObjectPrx = require("./ObjectPrx");
var __ice_HashMap = require("./HashMap");
var __ice_HashUtil = require("./HashUtil");
var __ice_ArrayUtil = require("./ArrayUtil");

var Ice = (function(_mod_Ice, undefined)
{

    _mod_Ice.RouterPrx = function()
    {
        __ice_ObjectPrx.call(this);
    }
    _mod_Ice.RouterPrx.prototype = new __ice_ObjectPrx();
    _mod_Ice.RouterPrx.prototype.constructor = _mod_Ice.RouterPrx;
    _mod_Ice.RouterPrx.checkedCast = function(__prx, __facet, __ctx)
    {
    }
    _mod_Ice.RouterPrx.uncheckedCast = function(__prx, __facet)
    {
    }

    /// <summary>
    /// The Ice router interface.
    /// Routers can be set either globally with
    /// Communicator.setDefaultRouter, or with ice_router on specific
    /// proxies.
    /// </summary>
    
    _mod_Ice.Router = function()
    {
        __ice_Object.call(this);
    }
    _mod_Ice.Router.prototype = new __ice_Object();
    _mod_Ice.Router.prototype.constructor = _mod_Ice.Router;
    _mod_Ice.Router.__ids = [
        "::Ice::Object",
        "::Ice::Router"
    ];
    _mod_Ice.Router.prototype.ice_ids = function(current)
    {
        return _mod_Ice.Router.__ids;
    }

    _mod_Ice.Router.ice_staticId = function()
    {
        return _mod_Ice.Router.__ids[1];
    }
    _mod_Ice.Router.prototype.getClientProxy = __ice_Object.prototype.__notImplemented;
    _mod_Ice.Router.prototype.getServerProxy = __ice_Object.prototype.__notImplemented;
    _mod_Ice.Router.prototype.addProxy = __ice_Object.prototype.__notImplemented;
    _mod_Ice.Router.prototype.addProxies = __ice_Object.prototype.__notImplemented;

    _mod_Ice.Router.prototype.toString = function()
    {
        return "[object Ice::Router]";
    }

    _mod_Ice.RouterPrx.prototype.getClientProxy = function(__ctx)
    {
    }

    _mod_Ice.RouterPrx.prototype.getServerProxy = function(__ctx)
    {
    }

    _mod_Ice.RouterPrx.prototype.addProxy = function(proxy, __ctx)
    {
    }

    _mod_Ice.RouterPrx.prototype.addProxies = function(proxies, __ctx)
    {
    }

    return _mod_Ice;
}(Ice || {}));

module.exports.Ice = Ice;
