// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `Hello.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, name)
{
    var __m = function(global, module, exports, require)
    {
        require("Ice/Object");
        require("Ice/ObjectPrx");
        require("Ice/TypeRegistry");
        require("Ice/HashMap");
        require("Ice/HashUtil");
        require("Ice/ArrayUtil");
        require("Ice/StreamHelpers");
        
        var Ice = global.Ice || {};
        var Demo = global.Demo ||  {};

        Demo.Hello = Slice.defineObject(
            function()
            {
                Ice.Object.call(this);
            },
            Ice.Object, undefined, 0,
            [
                "::Demo::Hello",
                "::Ice::Object"
            ],
            -1, undefined, undefined, false);

        Demo.HelloPrx = Slice.defineProxy(Ice.ObjectPrx, Demo.Hello.ice_staticId);

        Demo.HelloPrx.prototype.sayHello = function(delay, __ctx)
        {
            return Ice.ObjectPrx.__invoke(this, "sayHello", 2, 0, __ctx,
                function(__os)
                {
                    __os.writeInt(delay);
                }, null, null);
        };

        Demo.HelloPrx.prototype.shutdown = function(__ctx)
        {
            return Ice.ObjectPrx.__invoke(this, "shutdown", 0, 0, __ctx, null, null, null);
        };
        global.Demo = Demo;
    };
    return (module === undefined) ? this.Ice.__defineModule(__m, name) : 
        __m(global, module, module.exports, module.require);
}
(typeof module !== "undefined" ? module : undefined, "Hello"));
